# -*- coding: utf-8 -*-
"""Movie_Data_Analysis_Netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MVgIP5viTH4WBJ3ZDvDdjCOZ_dNJ5d3B
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('mymoviedb.csv', lineterminator='\n')

df.head()

df.info()

df['Genre'].head()

df.duplicated()

df.duplicated().sum()

df.describe()

"""Exploration Summary

*   We have a dataframe consisting of 9827 rows and 9 columns.
*   Our dataset look a bit tidy with no NaNa nor duplicated values.
*   Release Date column needs to be casted into date time and to extract only the year value.
*   Overview, Original_Language and Poster-Url would't be so useful during analysis, so we'll drop them.
*   There is noticable outlier in Popularity column.
*   Vote_Average better be categorised for proper analysis.
*   Genre column has comma saperated values and white spaces that needs to be handled and casted into catefory. Exploration Summary


"""

df['Release_Date'] =  pd.to_datetime(df['Release_Date'])
print(df['Release_Date'].dtypes)

df['Release_Date'] = df['Release_Date'].dt.year
df['Release_Date'].dtypes

df.head()

"""Dropping the columns"""

cols = ['Overview', 'Original_Language', 'Poster_Url']

df.drop(cols, axis = 1, inplace = True)
df.columns

df.head()

"""**Categorizing `Vote_Average` column**

We could cut the Vote_Average values and make 4 categories: `popular` `average` `below_avg` `not_popular` to describe it more using `categorize_col()` function provided above.


"""

def categorize_col (df, col, labels):
    edges = [df[col].describe()['min'],
             df[col].describe()['25%'],
             df[col].describe()['50%'],
             df[col].describe()['75%'],
             df[col].describe()['max']]

    df[col] = pd.cut(df[col], edges, labels = labels, duplicates='drop')
    return df

labels = ['not_popular', 'below_avg', 'average', 'popular']
categorize_col(df, 'Vote_Average', labels)
df['Vote_Average'].unique()

df.head()

df['Vote_Average'].value_counts()

df.dropna(inplace = True)
df.isna().sum()

df.head()

"""We did split genres into a list and then explode our dataframe to have only one genre per row for each movie."""

df['Genre'] = df['Genre'].str.split(', ')
df=df.explode('Genre').reset_index(drop=True)
df.head()

#casting column into category

df['Genre'] = df['Genre'].astype('category')
df['Genre'].dtypes

df.info()

df.nunique()

"""#Data Visualization"""

sns.set_style('whitegrid')

"""What is the most frequent genre of movies released on Netflix?"""

df['Genre'].describe()

sns.catplot(y = 'Genre', kind = 'count', data = df, order = df['Genre'].value_counts().index,
            color = '#4287f5')
plt.title('Most Frequent Genre')
plt.show()

"""Which has highest votes in vote avg column?"""

df.head()

sns.catplot(y = 'Vote_Average', kind = 'count', data = df, order = df['Vote_Average'].value_counts().index,
            color = '#4287f5')
plt.title('Highest Votes')
plt.show()

"""What movie got the highest popularity? What's its genre?

"""

df[df['Popularity'] == df['Popularity'].max()]

"""What movie got the lowest popularity? What's its genre?

"""

df[df['Popularity'] == df['Popularity'].min()]

"""Which year has the most filmmed movies?"""

df['Release_Date'].hist()
plt.title('Most Filmmed Year')
plt.show()

"""# Conclusion

---



**Q1. What is the most frequent genre in dataset?**

Drama genre is the most frequent genre in our dataset and has appeared more than `14%` of times among `19` other genres


**Q2. What genres has highest votes?**

We have `25.5%` of our dataset with popular vote (`6520 rows`). Drama again gets the highest popularity among fans by being having more than 18.5% movies.

**Q3. What movie got the highest popularity? what's its genre?**

`Spider-Man`: No way home has the highest popularity rate in our dataset and it has genresof Action, Adventureand Science Fiction.

**Q4. What movie got the lowest popularity? what's its genre?**

`The United States`, thread has the highest lowest rate in our dataset and it has genres of music, drama, war, sci-fi and history.

**Q4. Which year has the most filmmed movies?**

Year `2020` has the highest filmming rate in our dataset.
"""
